GET {{url}}/creations/tz1VgpmwW66LCbskjudK54Zp96vKn2cHjpGN
Accept: application/json
x-api-key: ZIMcGcGQ2s85G8ZTlwu3w5BvIJoowvt9aTlS9V96

###

GET {{url}}/collections/tz1VgpmwW66LCbskjudK54Zp96vKn2cHjpGN
Accept: application/json
x-api-key: ZIMcGcGQ2s85G8ZTlwu3w5BvIJoowvt9aTlS9V96

###

GET {{url}}/swaps/tz1VgpmwW66LCbskjudK54Zp96vKn2cHjpGN
Accept: application/json
x-api-key: ZIMcGcGQ2s85G8ZTlwu3w5BvIJoowvt9aTlS9V96

###

GET {{url}}/objkts/59894
Accept: application/json
x-api-key: ZIMcGcGQ2s85G8ZTlwu3w5BvIJoowvt9aTlS9V96

###

GET {{url}}/objkts/59894/swaps
Accept: application/json
x-api-key: ZIMcGcGQ2s85G8ZTlwu3w5BvIJoowvt9aTlS9V96

###

GET {{url}}/collectors/44295
Accept: application/json
Cache-Control: no-cache
Access-Control-Max-Age: 0
x-api-key: ZIMcGcGQ2s85G8ZTlwu3w5BvIJoowvt9aTlS9V96

###
